### ISSUE TITLE
Can't get more than 100 rows with AWS SDK S3 registerStreamWrapper() 

### ISSUE THREAD

**Issue by SamCritch** [parsecsv/parsecsv-for-php#107]
Hi. Using the [S3 Stream Wrapper](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-s3-stream-wrapper.html) and a parseCSV() method $scv->auto('s3://bucket_name/filename') to pull a file from Amazon S3 I can get the first 100 lines of any CSV file, but no more. Has anyone else experienced the same? This happens whatever I set an offset and limit to (unless it's smaller than 100).

The other weird thing is that the last line has one less field in it that the others....

Any ideas how I fix this? I've tried adding a seekable context and all sorts of different settings for the offset and limit, but no luck. I thought this might be due to a fixed number of bytes being read, but I've tried editing the CSV file with different numbers of bytes in the rows (different length fields) and it always stops on the 100th line, always misses the last field in that line (returns an array with _n -1_ elements instead of the _n_ elements in all the previous lines).

**Comment by Fonata** [comment]
Do you get the full content via file_get_contents()? If yes, you could give the string content instead of the URL to parseCSV.

**Comment by Fonata** [comment]
I don't think that 100 is a magic number here. Maybe some buffer's size coincidentally results in 100 lines of CSV. Please have a look at issue #69 for an example of partially reading the file line by line. You can use `ftell` and `fgets` to iterate.

**Comment by Fonata** [comment]
I think this issue may be a duplicate of the already solved #147.
