### ISSUE TITLE
File Conversion Error Please Fix it when i wirte located cell in 0 then its work also some unicode csv file dont read print just name so please fix it soon if possible

### ISSUE THREAD

**Issue by faizanjafri** [parsecsv/parsecsv-for-php#109]
Notice:  iconv(): Detected an illegal character in input string in C:\xampp\htdocs\newchk\class\parsecsv.lib.php on line 858
![image](https://user-images.githubusercontent.com/32553171/35173832-b266798e-fd8e-11e7-8b2a-ee2f6cfbdcb4.png)

**Comment by Fonata** [comment]
Hi faizanjafri , 

There seem to be several topics here:
- ``iconv()`` doesn't accept the input. This can be caused by 
  1. your environment as ``iconv()`` is an external library not fully compiled into PHP. As a remedy, I will add a new field ``use_mb_convert_encoding`` to ParseCSV. 
  2. Or it can be caused by specifying or detecting a wrong encoding
  3. The encoding of your file might actually be broken
- write located cell in 0: what did you expect and what happened instead? Right now I don't understand this aspect at all.

Please paste your relevant source code and attach the CSV file you wanted to work with. Feel free to censor code and data if some information should stay private.

**Comment by faizanjafri** [comment]
i have do this thn its working
![image](https://user-images.githubusercontent.com/32553171/35274221-1aa10b10-005d-11e8-8708-c354538bbbdd.png)

**Comment by faizanjafri** [comment]
if($extension == 'csv')
                      {

                        require_once('class/parsecsv.lib.php');
                          $info = pathinfo($_FILES['employee_file']['name'][$i]);
                          $webname = $info['filename'];
                          $select = "SELECT * FROM website WHERE website = '".$webname."'";
                          $runQuery = mysqli_query($connect, $select);
                          while($row = mysqli_fetch_array($runQuery))
                          {
                            $account_id = $row['user_id'];
                            $website    = $row['website'];
                            if($website == $webname)
                            {
                               
                               //var_dump($valid);
                              //$row=1;
                              # create new parseCSV object.
                              $csv = new parseCSV();
                              # Parse '_books.csv' using automatic delimiter detection...
                              $csv->auto($_FILES["employee_file"]["tmp_name"][$i]);
                              # ...or if you know the delimiter, set the delimiter character
                              # if its not the default comma...
                              // $csv->delimiter = "\t";   # tab delimited
                              # ...and then use the parse() function.
                              // $csv->parse('_books.csv');
                              # Output result.
                              // print_r($csv->data);
                               foreach ($csv->data as $key => $row)
                               {
                                  $tags = htmlentities($row['Tags']);
                                  $days = htmlentities($row['Days']);
                                  $newDate = date("m/d/Y", strtotime($days));
                                  $adRequest = htmlentities($row['Ad requests']);
                                  $aR = str_replace(',','',$adRequest);
                                  $matchReq = htmlentities($row['Matched requests']);
                                  $mR = str_replace(',','',$matchReq);
                                  $coverage = htmlentities($row['Coverage']);
                                  $clicks = htmlentities($row['Clicks']);
                                  $click = str_replace(',','',$clicks);
                                  $ctr = htmlentities($row['CTR']);
                                  $estRev = htmlentities($row['Estimated revenue']);
                                  $eRev = str_replace(',','',$estRev);
                                  $adImpression = htmlentities($row['Ad impressions']);
                                  $aI = str_replace(',','',$adImpression);
                                  $ecpm = htmlentities($row['Ad eCPM']);
                                  //$user_id = '1';
                                  //$webs = $web;
                                  $published = '0';
                                  $status = 'unpaid';
                                  $del_status = 'not_delete';

                                  $insert = "INSERT INTO `uploadfile`(`days`, `tag`, `ad_request`, `match_request`, `coverage`, `click`, `ctr`, `ctr_change`, `revenue`, `new_revenue`, `impression`, `cpm`, `cpm_new`, `user_id`, `website`, `published`, `status`, `del_status`) VALUES ('$newDate','$tags','$aR','$mR','$coverage','$click','$ctr','$ctr','$eRev','$eRev','$aI','$ecpm','$ecpm','$account_id','$website','$published','$status','$del_status')";

                                  mysqli_query($connect, $insert);              
                               }

                               $deleteDays = "DELETE FROM uploadfile WHERE days = 'Days'";
                                mysqli_query($connect, $deleteDays);

                                $deletedays = "DELETE FROM uploadfile WHERE days = 'days'";
                                mysqli_query($connect, $deletedays);

                                $deleteDAYS = "DELETE FROM uploadfile WHERE days = 'DAYS'";
                                mysqli_query($connect, $deleteDAYS);

                                $deleteReq = "DELETE FROM uploadfile WHERE ad_request = '0.0000'";
                                mysqli_query($connect, $deleteReq);
                              
                            }
                          }
                      }

**Comment by faizanjafri** [comment]
Thats my code but it not read all data from csv sheets

**Comment by Fonata** [comment]
From the screenshot of the code, I believe that no change is necessary in the library itself. 

Please set `$csv->output_encoding = "ISO-8859-1//IGNORE"` in your code instead.
