### ISSUE TITLE
Error. Eats a line if CSV without field names 

### ISSUE THREAD

**Issue by SobakaEbaka** [parsecsv/parsecsv-for-php#117]
**example:** 
    $file="1997,Ford,E350,\"ac, abs, moon\",3000.00";   
    $csv = new parseCSV();
    $csv->fields =  ['col1', 'col2','col3','col4','col5'];
    $csv->auto($file);
    var_dump($csv->data );

**Result:** 
    array(0) { }

**Comment by SobakaEbaka** [comment]
Ohh...  sorry 
 $csv -> heading =false; !

**Comment by Fonata** [comment]
I'm glad you figured it out yourself. 

If you have any further questions feel free to create another issue.
