### ISSUE TITLE
$csv->output doesn't work

### ISSUE THREAD

**Issue by shinkle-orbytel** [parsecsv/parsecsv-for-php#132]
I have a very simple test case for generating CSV output based on some data.

require DIR_RESOURCES . '/parsecsv/parsecsv.lib.php';
$csv = new ParseCsv\Csv();
$output = $csv->output("test.csv", [0 => ['a', 'b', 'c'], 1 => ['d', 'e', 'f']], ['col1', 'col2', 'col3'], ',');

Causes the following: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The specified fields do not match any titles and do not match column count.' in C:\wamp64\www\harmony_3.0\resources\parsecsv\src\Csv.php:860

$titlesOnParse appears to be an empty array which is where the error is thrown. Shouldn't this work since the column counts match?

**Comment by Fonata** [comment]
@shinkle-orbytel Thank you for creating this issue! 

I have created pull request #133 to fix it.

**Comment by susgo** [comment]
The pull request is merged so this could be closed, couldn't it?
