### ISSUE TITLE
Update composer.json

### ISSUE THREAD

**Issue by ghost** [parsecsv/parsecsv-for-php#135]
Update the composer.json authors section. We now need to include @Fonata in it

**Comment by tresero** [comment]
The current composer doesn't pull the latest source. I'm not a composer expert so I'm not sure what to fix. 

For example, the current composer pull is missing stuff. 

For example: Call to undefined method ParseCsv\\Csv::getTotalDataRowCount()

**Comment by susgo** [comment]
@tresero Could you please provide your composer.json for this line?

**Comment by tresero** [comment]
Here you go. This is a one off application that just parses reports, so not
much in it.

{
    "require": {
        "league/csv": "*",
        "phpoffice/phpspreadsheet": "dev-develop",
        "parsecsv/php-parsecsv": "^1.0"
    }
}

**Comment by susgo** [comment]
Don't tested it yet but maybe there is a bug with our release tags @Fonata?

@tresero For the moment setting "dev-master" for this package in your composer.json should solve the problem. We come back to you when we have tested if there is something wrong with the tags.

**Comment by Fonata** [comment]
@tresero Indeed, telling us is important! Thank you! I'll create a new release by tomorrow, when PR #147 is merged.

**Comment by Fonata** [comment]
The [new release](https://github.com/parsecsv/parsecsv-for-php/releases/tag/1.1.0) is out! Despite my minor contributions I granted @ghost's wish and added @susgo and me to the author list in composer.json.
