### ISSUE TITLE
no valid autoparsing if file has multiple empty lines on end

### ISSUE THREAD

**Issue by kPinder** [parsecsv/parsecsv-for-php#141]
with file: 
[example_no_parse_multipler_empty_lines.csv.zip](https://github.com/parsecsv/parsecsv-for-php/files/1906321/example_no_parse_multipler_empty_lines.csv.zip)

**Comment by Fonata** [comment]
Dear kPinder,

Thanks for opening this issue & welcome to GitHub! I will add your file to the tests and adjust the parsing.
