### ISSUE TITLE
Delete a row

### ISSUE THREAD

**Issue by gesundelehre** [parsecsv/parsecsv-for-php#143]
Is there a way to delete a certain row

If not, would it be possible to create a method that could be called like this?

```
$csv = new ParseCsv\Csv();
$csv->sort_by = 'id';
$csv->parse('data.csv');
$csv->delete_row_of_id(4) //to delete row with the id 4
$csv->save(); //overwrite file without the row of id 4
```

Thanks in advance for the reply

**Comment by Fonata** [comment]
Dear @gesundelehre thanks for asking! You can use `unset($csv->data[$row_index]);` before saving. In this example, `$row_index` is an integer indicating which row to delete. 

To look for an id in the data, let me assume you have a header row in your CSV, and the column to search for the id is called just id. Then you can use something like `$row_index = array_search(4, array_column($csv->data, 'id'));`
