### ISSUE TITLE
Character 'R' is converting to comma(,)

### ISSUE THREAD

**Issue by tejashapani** [parsecsv/parsecsv-for-php#145]
Hello,

I am using ParseCSV class to upload and import data from CSV.

It is converting character 'R' to comma.
for example, if the string in csv is 'form' then it converts this to 'fo,m'
or 'release' to ',elease'

How can i avoid this?

**Comment by tejashapani** [comment]
Hi @susgo ,

Thanks for reaching out to me.

Below is the code i am using:
`include_once 'parsecsv.lib.php';
$csv = new parseCSV();
$csv->auto('Waiver.csv');

foreach ($csv->data as $row):
    $rowData = @implode(",", $row);

    // Having insert query here.
    // Save each row data as one single record in database.

endforeach;`

The parsecsv class file is here:
https://www.dropbox.com/s/dy55l4ymc3fw4bn/parsecsv.lib.php?dl=0

And the CSV file i am using to import is here:
https://www.dropbox.com/s/rl279pbml0sb534/Waiver.csv?dl=0

Thanks for the help.

**Comment by Fonata** [comment]
Interesting! Usually, this kind of behavior should be prevented by the `$auto_non_chars` field. 

@tejashapani would you be ok with us adding your CSV file to our automated tests? Feel free to test with the current master branch of this repo. Also, you are welcome to send us a merge request with either just the test or also the bug fix (if we can reproduce it with the master - I haven't tried yet).

@susgo, @tejashapani  If you would like to take on this task, please assign yourself to this issue. I'd to the same, on Monday at the earliest.

**Comment by Fonata** [comment]
@tejashapani please try again with the master branch. 

I'll close this issue for now. If you also run into problems with the master branch, feel free to re-open it.
