### ISSUE TITLE
Header Content-Length with gzip in output method

### ISSUE THREAD

**Issue by Fivedark** [parsecsv/parsecsv-for-php#153]
Hi,

thanks for contributing this great lib.

We using gzip with ob_gzhandler in our framework and use the output function of parsecsv to show or download a generated csv file, but the browser shows an error.

The error is caused by setting the Content-Length for the non gzipped content. If I remove the Content-Length line (448), everything is working fine. 

I see three possible solutions:
1. stop setting the Content-Length
2. add an argument to prevent the output method from setting the Content-Length
3. calculate the correct Content-Length, if gzip is enabled

**Comment by Fonata** [comment]
@Fivedark: I see a 4th solution: You can use Apache's compression support. It will rewrite the Content-Length header.

**Comment by Fonata** [comment]
@Fivedark you can call `header('Content-Length')` again and it will overwrite the value that ParseCSV sets.
What I describe here is the default behaviour controlled by the `$replace` parameter of the ``header()`` function - see the [PHP documentation for header()](https://www.php.net/manual/en/function.header.php).
