### ISSUE TITLE
 add quotes

### ISSUE THREAD

**Issue by TwinMist** [parsecsv/parsecsv-for-php#155]
Hi, Great work on this. Can you tell me how i can add quote around the array value?

thanks

**Comment by susgo** [comment]
Hi! Sorry, I don't understand your use case. Do you have an example what you would like to have? The expected output? Or some source code you use at the moment? Thanks! And sorry for the late reply.

**Comment by TwinMist** [comment]
Need to export like  "value","value"
Thanks

**Comment by susgo** [comment]
I think the property `enclose_all` implements this. Please try:
```php
$csv = new ParseCsv\Csv();    
$csv->parse('data.csv');    
$csv->enclose_all = true;    // setting this parameter to true (default is false) solves your issue
$csv->save();   
```

Please close this issue if this solves your problem. Thanks!

**Comment by TwinMist** [comment]
Great that worked, thanks
