### ISSUE TITLE
change new line CR to CR/LF or LF

### ISSUE THREAD

**Issue by TwinMist** [parsecsv/parsecsv-for-php#163]
Hi
is there a way when saving to change how a new line is encoded either to LF or CR/LF

thanks

**Comment by Fonata** [comment]
Yes. Here is how:
1. Set the ``linefeed`` field, for example ``$csv_object->linefeed = "\n";``
2. Call one of the following: `save()`, `unparse()` or `output()`

I'll close this issue assuming your question is answered. If not, please re-open. If there is anything else we can help with, feel free to open another issue.
