### ISSUE TITLE
Readme recommends considering PHP's built-in functions

### ISSUE THREAD

**Issue by joshpowlison** [parsecsv/parsecsv-for-php#167]
PHP's built-in functions don't actually conform to the standards for CSV, which can cause a lot of problems in your code if you use those functions.

[PHP Bug #43225](https://bugs.php.net/bug.php?id=43225)
[PHP Bug #50686](https://bugs.php.net/bug.php?id=50686)

I'm referring to this line in the Readme:

> You may not need a library at all: before using ParseCsv, please make sure if PHP's own `str_getcsv()`, `fgetcvs()` or `fputcsv()` meets your needs.

I think mentioning that those functions don't conform to the standards could save some programmers a lot of trouble.

**Comment by osc2nuke** [comment]
I am the last want to go argue.
Respect to @geminorum for finding all the faults that can happen.
I think this package is very useful.
There are so many faulty CSV's.
Especially the ones without headings (WHYYYYYYYYYYYYY).
But that is not worst.
I got one with over 60 headings.
I would like a :
`$csv->fields_auto`

So when i start USE the csv (means before i use the file, and NOT have headings) it go make:
Col_1
Col_2
Etc...
Kinda like how phpMyAdmin does.

**Comment by Fonata** [comment]
@osc2nuke 
Thanks for your feedback. I am a bit lost as to what you need specifically. Maybe you can describe it in a different way? Are you looking for a ready-made GUI?

Please open a new issue, because I cannot see the connection with the README file yet.

**Comment by osc2nuke** [comment]
Yes, but i found '$csv->fields' does the trick.
