### ISSUE TITLE
write csv space delimited support

### ISSUE THREAD

**Issue by mckaygerhard** [parsecsv/parsecsv-for-php#169]
hi, i revise the docs and i wants to know if space delimited text are supported by this project?

**Comment by Fonata** [comment]
It depends on what you mean exactly:
- ParseCsv can use any character as a field separator using the `delimiter` property. If fields are separated by a single space (or tab `\n`) character, this is going to work with the `save()` function. You can start with the [save_to_file_without_header_row.php example](https://github.com/parsecsv/parsecsv-for-php/blob/master/examples/save_to_file_without_header_row.php) and add a line `$csv->delimiter = ' ';` before the `save()` call.
- ParseCsv cannot write what Excel and Calc call the "Fixed width" format. I suggest you google something like [fixed width data file php write](https://www.google.de/search?q=fixed+width+data+file+php+write).

**Comment by mckaygerhard** [comment]
thanks for the right response.. great php utility.. i' using any way! now i will take a look at  "fixed width data file php write." (there's no too much .. so i must made by my own)
