### ISSUE TITLE
Replace field names or set ones if missing

### ISSUE THREAD

**Issue by osc2nuke** [parsecsv/parsecsv-for-php#172]
I first want to explain what i attempt to do, so you understand the situation.
I am working on a so called "feed Manager".
Some of the feeds (csv's) do not contain headings.

What i try to do is:
Count the columns and assign a custom heading to the column i want the data from.

Not tested but:

    $csv = new ParseCsv\Csv();
    $csv->fields = ['id', 'name', 'category']
    $csv->parse('data.csv');

can it also be:

    $csv->fields[3] = 'my custom heading';

cause i not quite understand:

> Replace field names or set ones if missing

**Comment by susgo** [comment]
No sorry, this will not work at the moment

**Comment by osc2nuke** [comment]
Ok, thanks.
I solved it using just the default code.
One problem left is, as i use "custom headings"  (means my csv has NO headings), the csv is parsed skipping the first row.
`$csv->offset = 0`
Not work in this case.
Is there any solution for that?
Or do i miss a setting?

**Comment by osc2nuke** [comment]
I will close this and make a new request.
