### ISSUE TITLE
Custom headings ($this->fields)

### ISSUE THREAD

**Issue by osc2nuke** [parsecsv/parsecsv-for-php#173]
I tried some of the options, but i cannot get around it.
If i have a .csv that does NOT had any headings but assign them via:

`$csv->fields`

The FIRST row of the .csv is ignored, when i
 
`$csv->parse('my.csv')`

The setting:
`$csv->offset =  0`
is ignored, BUT:
`$csv->offset =  2`
not.

(i ask myself what is the use of the `$csv->fields` if not can read the whole .csv?)

**Comment by osc2nuke** [comment]
Sigh.......
It was my fault, i did not position `$csv->heading = false:` correctly.
Example and might usefully for others:

              
        $csv->offset = null;
        $csv->delimiter = $this->config['delimiter'];
        $csv->heading = false;
        //start custom code
        $file = file(DIR_FS_CATALOG . 'feeds/'.$this->config['url']);

        $fileHeaders = array();

        $lineArr = $this->pregSplit($file[0]);
       //check for custom headings, set up in db
        if(tep_not_null($this->custom_headings)){
            $JsonHeadings = json_decode($this->custom_headings);
            foreach($lineArr as $col => $text){
                if (isset($JsonHeadings->$col)){
                    $colCheck = $JsonHeadings->$col;
                    if (isset($this->fields[$colCheck])){
                        $fileHeaders[$col] = $this->fields[$colCheck];
                    }   
                }
            }

        }else{
           //we use the csv file headings
            foreach($lineArr as $col => $text){
                $colCheck = strtolower(trim($text));
                if (isset($this->fields[$colCheck])){
                    $fileHeaders[$col] = $this->fields[$colCheck];
                }
            }

        }

        unset($file[0]);
       //end custom code
        $csv->fields = $fileHeaders;
        
        $csv->parse('feeds/'.$this->config['url']);`

Sorry that i bugged you.

**Comment by Fonata** [comment]
No problem at all. Feel free to create an issue whenever we can help.
