### ISSUE TITLE
Cuts strings more 255 symbols

### ISSUE THREAD

**Issue by Mykola-Veryha** [parsecsv/parsecsv-for-php#175]
This library cuts strings more 255 symbols

**Comment by Fonata** [comment]
@Mykola-Veriga Thanks for opening an issue here. Where exactly did you run into problems? Can you post the code how you use the library? If relevant and possible, please also post the CSV file you worked with when you saw the problem.

**Comment by Mykola-Veryha** [comment]
Sorry, it was my mistake. The reason for the problem wasn't in this library.
