### ISSUE TITLE
PHP 7.4: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by fjf2002** [parsecsv/parsecsv-for-php#181]
Hello,

please replace in lines like these:

    $lch = $data{$strlen - 1};

curly braces with brackets, thanks!

cf. https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by Fonata** [comment]
@fjf2002 Thanks for opening the issue! Sorry, that this took so long to fix. 

Feel free to open an issue in the future.
