### ISSUE TITLE
detect encoding How To?

### ISSUE THREAD

**Issue by osc2nuke** [parsecsv/parsecsv-for-php#187]
I try to figure out how to use :
`$csv->encoding('UTF-16', 'UTF-8');`

My csv files vary from ISO-8859-1 till US-ASII.

The doc say i must load before parsing:
`$csv->encoding('UTF-16', 'UTF-8');`

But i must know before no?
so i can do something like:

`$detectedEncoding = $csv->detect_encoding();`
`$csv->encoding($detectedEncoding , 'UTF-8');`//and ignore if is already UTF-8

Does anyone know?
Thanks in advanced.

**Comment by Fonata** [comment]
Detecting the encoding is outside the scope of this library. 

You can use functions such as `mb_detect_encoding()`. 

Here is an example of how to use it:
````php
$filename = 'examples/people.csv';

$csv = new ParseCsv\Csv();
$csv->file_data = file_get_contents($filename);
$deteced_encoding = mb_detect_encoding($csv->file_data);
$csv->encoding($deteced_encoding);
$csv->auto();
````

I'll close this issue now. If you have any further questions, feel free to re-open and ask.
