### ISSUE TITLE
PHPUnit_Framework_TestCase.inc.php uses the same namespace as real PHPUnit TestCase class

### ISSUE THREAD

**Issue by SharkMachine** [parsecsv/parsecsv-for-php#188]
I'm using ParseCSV via composer on a project that uses PHPUnit 8 for unit testing.

I'm having some problems as `tests/PHPUnit_Framework_TestCase.inc.php` uses the same namespace as the real `TestCase` class.

I'm getting warnings about there being multiple definitions:

![image](https://user-images.githubusercontent.com/7488694/78744241-c01eea80-7969-11ea-9253-c82db37dbba8.png)

And code completion is completely broken on all of my test classes as a result:

![image](https://user-images.githubusercontent.com/7488694/78744300-e6448a80-7969-11ea-9fd2-0a129a349028.png)

Deleting the file from vendor folder does fix the problem, but it's still annoying to be forced to do that constantly.

![image](https://user-images.githubusercontent.com/7488694/78744418-2e63ad00-796a-11ea-8531-1a9875c3e7d6.png)

**Comment by Fonata** [comment]
Thanks for opening an issue here! 

As a quick work-around you can mark ParseCsv's `tests` directory as Excluded:  
![image](https://user-images.githubusercontent.com/6819464/78792311-43affa00-79b1-11ea-9170-4011f303c32e.png)

**Comment by SharkMachine** [comment]
@Fonata That's a lot better than my workaround, thanks. What I'd like even more, would be 2.0 with no PHP 5.x compatibility. You could even go with only supporting PHP 7.2+ as that's the oldest officially supported version at the moment.

If you are accepting PRs for that, I'm willing to do that.
