### ISSUE TITLE
Cannot parse CSV files with BOM (UTF-8)

### ISSUE THREAD

**Issue by amivag** [parsecsv/parsecsv-for-php#193]
As the title says. Try parsing a CSV file with BOM signature (aka Excel CSV). The library fails to extract the data properly.

**Comment by Fonata** [comment]
Please attach an example file and the code you used to open it. Thanks.

**Comment by amivag** [comment]
I am closing this for now because it's been a long time and I don't have access to the original code.

**Comment by tchapi** [comment]
Still the case right now:

[test_with_BOM.csv](https://github.com/parsecsv/parsecsv-for-php/files/6590814/test_with_BOM.csv)

This code is not working:

```php
$csv = new Csv();
$csv->delimiter = ';';
$csv->header = true;
$csv->parseFile('test_with_BOM.csv'); //$filepath);
var_dump($csv->data);
```

**Comment by tchapi** [comment]
```
❯ file /test_with_BOM.csv
/test_with_BOM.csv: UTF-8 Unicode (with BOM) text, with CRLF line terminators
```
