### ISSUE TITLE
typo in master - readme file

### ISSUE THREAD

**Issue by nerdbachu** [parsecsv/parsecsv-for-php#195]
In the below sentence

You may not need a library at all: before using ParseCsv, please make sure if PHP's own str_getcsv(), fgetcvs() or fputcsv() meets your needs.

`fgetcsv` function is misspelt.

**Comment by Fonata** [comment]
@nerdbachu Thanks, I fixed it! 

If you find similar errors anywhere on GitHub (not just this library), you can also edit the file directly, using the pen icon. This allows you to open a pull request to let the maintainers accept the change directly. No pressure though, as resolving an issue is just a little more work, not much.
