### ISSUE TITLE
Syntax Error unexpected 'class' (T_CLASS)

### ISSUE THREAD

**Issue by kiwigringo** [parsecsv/parsecsv-for-php#197]
I'm running on php 7.4x and on attempting to import a CSV file received this error:

Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' (line 63 of /parsecsv-for-php/src/extensions/DatatypeTrait.php)

A quick Google search on this error seems to indicate it's usually associated with older versions of PHP, but in this case php 7.4x is still a fully supported version.
Are there any version dependencies that could cause this?

**Comment by Fonata** [comment]
Thanks for reporting this problem! Which release or version of ParseCsv do you use?

**Comment by kiwigringo** [comment]
Version 1.2.0

**Comment by kiwigringo** [comment]
Resolved the issue. The control panel for the server was reporting PHP version > 7, but was actually applying a 5.4.x version. Fixed this and it works.

**Comment by Fonata** [comment]
Thanks for your feedback :+1:
