### ISSUE TITLE
Deprecated message in ParseCsv 1.3

### ISSUE THREAD

**Issue by Melebius** [parsecsv/parsecsv-for-php#201]
Since I upgraded to ParseCsv 1.3, I keep getting the following message whenever I run ParseCsv in my PHP script:

> PHP Deprecated:  Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead. in myproject/vendor/parsecsv/php-parsecsv/src/Csv.php on line 406

I am not directly using `parse()` anywhere in my code, I am using ParseCsv in the following way, complying with the [documentation](https://github.com/parsecsv/parsecsv-for-php/blob/master/README.md#example-usage):
```php
$csv = new \ParseCsv\Csv($filename);
foreach($csv->data as $item) {
  // ...
```

Moreover, the error message is written to STDOUT in addition to STDERR, so I need to remove it manually from my script’s output.

**Comment by Fonata** [comment]
Thanks for letting us know and creating an issue here. :blush: 

Please rewrite your code like this:
```php
$csv = new \ParseCsv\Csv();
$csv->parseFile($filename);
foreach($csv->data as $item) {
...
```

You are supplying the filename in the constructor. This is deprecated, but the message you receive is not clear. Everyone is welcome to contribute a pull request that produces a better message for your situation. Currently, ParseCsv doesn't track how `parse()` ended up with the filename, so `parse()` doesn’t know it comes from the constructor.

The following may not apply to you - I don't know your infrastructure. From a security point of view it is very important that PHP errors are only visible to privileged members of your organization. In particular, you need to configure your server in such a way that errors are not visible on the web.

**Comment by mylemans** [comment]
@Fonata $csv->parseFile('data.tsv');
print_r($csv->data);

That seems to be broken. parseFile returns the 'rows' but $csv->data is NEVER assigned! At first I thought maybe this was an intentional change, but since you are using it here as an example I assume it ain't?

**Comment by Melebius** [comment]
@Fonata, thanks for your reply. I tried the solution you suggested but I’ve got the problem mentioned by @mylemans: `$csv->data` contains nothing after using `$csv->parseFile($filename)`.

**Comment by mylemans** [comment]
@Melebius For now, you can just take the output from the parseFile function, it will contain what you would normally to be assigned to ->data

**Comment by Fonata** [comment]
The assignment to `->data` will be addressed in the next release, planned for the end of May. You can see my proposed changes in #202.
