### ISSUE TITLE
how can i parse csv data from string

### ISSUE THREAD

**Issue by Mkurbanov** [parsecsv/parsecsv-for-php#203]
Hi.
how can i parse csv data from string. Like this:
`$csv->parseFile('data.tsv');`
to
`$csv->parseString($data);`

Thx. In advance.

**Comment by Fonata** [comment]
The function you are looking for is `$csv->parse($data);`. 

From your example I assume that the field separator is a tab character. Here is a full example: 

```php
$data = file_get_contents('data.tsv');
$csv->delimiter = "\t";
$csv->parse($data);
```

Alternatively, you can use `$csv->autoDetectionForDataString($data);` to detect the field separator and line feed characters.

Feel free to re-open this issue if you have questions about this particular problem. If you have other questions, please open a separate issue. Thanks!
