### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by ErikThiart** [parsecsv/parsecsv-for-php#218]
Hello, just checking, we need to upgrade to PHP 8.3, I just want know if this library supports it?

If not, I can help, just need to know where to begin to look.

**Comment by gogowitsch** [comment]
Yes, PHP 8.3 is supported.

**Comment by gogowitsch** [comment]
We support PHP versions 5.5 - 8.3 with the same code base. Thanks for the ping! I updated the README to show PHP 8.3 support.

**Comment by ErikThiart** [comment]
Awesome sauce. 

Brilliant library, genuinely thank you for supporting it.
