### ISSUE TITLE
Heading and offset

### ISSUE THREAD

**Issue by EvoWebFrance** [parsecsv/parsecsv-for-php#42]
Hello,

I'm using ParseCSV for big files (169Mo and up to 97000 records) and I must use the offset/limit feature to parse step by step.
If my CSV page has a heading, for an offset of 0 I have my array with keys as head names, but if my offset is set more than 0, I lost the keys as head names.
I suggest to modify the code like this in _parse_string_ function:

``` php
if ( $this->heading && empty($head) ) {
    $head = $row;
} elseif ( $this->_validate_offset($row_count) && $this->_validate_row_conditions($row, $this->conditions) ) {
    if ( empty($this->fields) || (!empty($this->fields) && (($this->heading && $row_count > 0) || !$this->heading)) ) {
        if ( !empty($this->sort_by) && !empty($row[$this->sort_by]) ) {
            if ( isset($rows[$row[$this->sort_by]]) ) {
                $rows[$row[$this->sort_by].'_0'] = &$rows[$row[$this->sort_by]];
                unset($rows[$row[$this->sort_by]]);
                for ( $sn=1; isset($rows[$row[$this->sort_by].'_'.$sn]); $sn++ ) {}
                $rows[$row[$this->sort_by].'_'.$sn] = $row;
            } else $rows[$row[$this->sort_by]] = $row;
        } else $rows[] = $row;
    }
}
```

With this modification, I have always the good head names in my array keys.

**Comment by tmetzger** [comment]
Just stumbled across this. I had the same issue as OP - parsing large files, must use offsets, only the first offset (zero) had headers!

I made the above adjustment, and all is working well now. So the code seems good, at least in this use case.

**Comment by SamCritch** [comment]
Assuming I understand the problem, I solved this by first setting offset to 0 and limit to 1, then parsing the header line of the file:

`$header_fields = array_keys($csv->data[0]);`

Once that's done I parse again in a loop with required offset and limit, but do the following for each loop to set the headers for each parse:

`$csv->fields = $header_fields;`
