### ISSUE TITLE
Message: iconv(): Detected an incomplete multibyte character in input string

### ISSUE THREAD

**Issue by alwinaugustin** [parsecsv/parsecsv-for-php#48]
When I use 

$this->csv->encoding('UTF-16', 'UTF-8');
$this->csv->parse($file_path);

It is giving me this error. 

What about using this instead in the library ?

iconv(mb_detect_encoding($text, mb_detect_order(), true), "UTF-8", $text);

This will detect the incoming encoding and convert to UTF - 8

**Comment by williamknauss** [comment]
No response --- closing
