### ISSUE TITLE
Autoloader not working

### ISSUE THREAD

**Issue by odan** [parsecsv/parsecsv-for-php#50]
Hello

I'm using composer to include parsecsv-for-php.
I added "parsecsv/php-parsecsv": "0.4.5" to my composer.json file.
But the class cannot loaded with the PSR autoloader.

Error: Class 'parseCSV' not found	

PSR says: The fully-qualified namespace and class is suffixed with .php when loading from the file system.

I think the filename must be renamed from "parsecsv.lib.php" to "parseCSV.php"

Much better would be (to be compliant with PSR-1): Class names MUST be declared in StudlyCaps.
e.g.
Classname = ParseCSV
Filename = ParseCSV.php

**Comment by williamknauss** [comment]
Good Day Odan,
While I agree the library name should be renamed that shouldn't prevent composer from autoloading the class. Would you mind sharing your composer file?

**Comment by odan** [comment]
Hello williamknauss

Sorry, it was just an autoloading issue in combination with composer and CakePHP 2.x.
CakePHP doesn't fully support autoloading. I've had to add a small workaround in my CakePHP project (core.php):

```php
// Remove and re-prepend CakePHP's autoloader as composer thinks it is the most important.
// See https://github.com/composer/composer/commit/c80cb76b9b5082ecc3e5b53b1050f76bb27b127b
spl_autoload_unregister(array('App', 'load'));
spl_autoload_register(array('App', 'load'), true, true);
```
