### ISSUE TITLE
PSR coding style

### ISSUE THREAD

**Issue by odan** [parsecsv/parsecsv-for-php#51]
Hello, I like your CSV parser and I would like to contribute to this project.
What do you think about rewriting the code to PSR-2 style?

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Comment by williamknauss** [comment]
Hi @odan,
Sorry for the tardy response here. We were planning on doing a huge rewrite of the basic parse api but that is going to be put off for a while so feel free to submit a PR with PSR-2 coding style.

**Comment by williamknauss** [comment]
Hi @odan,
While the library location isn't PSR I did run the code through the CS-Fixer for cleanup.
