### ISSUE TITLE
flock causes the script to abort

### ISSUE THREAD

**Issue by alexschwarz89** [parsecsv/parsecsv-for-php#53]
The following line causes the script to abort (there is no error message) on OS X Yosemite 10.10.2 running XAMPP with PHP 5.5.14.

    flock($fp, $lock);

It is defined inside parsecsv.lib.php inside the function _wfile
If I comment this line, everything works fine.

**Comment by williamknauss** [comment]
Hi @alexschwarz89,
I'm not really sure why flock is in there at this point. Feel free to remove it and do a PR.

**Comment by williamknauss** [comment]
Hi @alexschwarz89,
Got this done checkout #54. Let me know how this works for you.

Thanks
