### ISSUE TITLE
Use MS Excel's "sep=" to detect the delimiter

### ISSUE THREAD

**Issue by hakimio** [parsecsv/parsecsv-for-php#60]
Microsoft Excel uses different default delimiter based on the current OS locale. For example, if locale is set to US it will use "," as delimiter and if it's Danish, it will use ";" by default. It works like that because many European languages use comma for decimal notation ("1,23" instead of "1.23" like in US).
However, the default delimiter can be specified in the file by putting "sep=," as the first line (in this case it will use comma as the delimiter no matter what OS locale is set to). It would be great if this library could do the same to try to detect the default delimiter and then skip the first line of the file if it's used to specify the delimiter.

**Comment by jimeh** [comment]
I was not aware Excel did that. Would you happen to have a few examples that came out of Excel on hand you can share? If not I'll install Excel when I get some free time.

**Comment by hakimio** [comment]
I am not sure what kind of example you are looking for. The difference between the CSV files when different locales are used is only the delimiter. You can find more info [here](https://support.office.com/en-za/article/Import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba#bmchange_the_separator_in_all__csv_text).

**Comment by hakimio** [comment]
Here is a simple patch to illustrate what I want to achieve: http://pastebin.com/qara54N1

**Comment by Piskvor** [comment]
Here's my take on this potential feature: https://github.com/parsecsv/parsecsv-for-php/pull/73

**Comment by hakimio** [comment]
@Piskvor I like your _get_delimiter_from_sep() method, but I don't think it's a good idea to use it only when normal automatic delimiter detection fails. If normal detection succeeds and you have "sep=;" as the first line in the file, the library will use "sep=;" as the column header which is a pretty bad idea.

**Comment by Piskvor** [comment]
Actually, if delimiter detection succeeds, `$this->delimiter` will be populated at line 598, and the entire code block will be skipped. https://github.com/parsecsv/parsecsv-for-php/pull/73/files#diff-0659d2647a02cc831a903e1476a35e26R598

**Comment by Piskvor** [comment]
Aha, I see your point now. Hmm, perhaps this could be a) made optional, or b) checked even before the other heuristics. (But let's discuss the changeset in its discussion; it's - IMHO - more readable than here, as it's not specifically relevant to the feature, rather to its implementation).

**Comment by Fonata** [comment]
Thanks everyone! This is in the master branch now.

**Comment by assisfery** [comment]
This was solved/implemented?

**Comment by Fonata** [comment]
Yes, it is implemented. See the commit 39c713c4d0254f4ea9d9efd4872fa33587996595 for the implementation detail. Call `auto()` for a CSV file and the sep= line will be used if present.
