### ISSUE TITLE
Splitting rows unexpectedly.

### ISSUE THREAD

**Issue by mubin-khalid** [parsecsv/parsecsv-for-php#61]
I'm been working with this and found that whenever there is a zero in the line, it breaks the sequence.
Here.
I've this string in the file
http://www.amazon.com/ROX-Ice-Ball-Maker-Original/dp/B00MX59NMQ/ref=sr_1_1?ie=UTF8&qid=1435604374&sr=8-1&keywords=rox+ice+molds

I expected this output
[link] => http://www.amazon.com/ROX-Ice-Ball-Maker-Original/dp/B00MX59NMQ/ref=sr_1_1?ie=UTF8&qid=1435604374&sr=8-1&keywords=rox+ice+molds

but unfortunately getting this one,

[0] => Array
        (
            [link] => http://www.amazon.com/ROX-Ice-Ball-Maker-Original/dp/B
            [1] => 
            [2] => MX59NMQ/ref=sr_1_1?ie=UTF8&qid=14356
            [3] => 4374&sr=8-1&keywords=rox+ice+molds
        )

**Comment by jens-chorus** [comment]
I can confirm this bug. You can work around this by setting the delimiter manually however.
