### ISSUE TITLE
how to convert 9.00E+18 numbers into simple numbers

### ISSUE THREAD

**Issue by tahseen2k8** [parsecsv/parsecsv-for-php#63]
hey folks 
I have used you lib it is really awesome every thing is working fine in it..
but facing only one issue there is a field which is containing 13 digit integer value '12123123123123xx'
which is shown 9.00E+18 like this in sheet . When i render and insert it into db it insert the data like this 9.00E+18  so how to formate them into real value which we insert into it..
thanks in advance ..

**Comment by jimeh** [comment]
Hey @tahseen2k8,

Is this when you parse or build CSV data?

If it's when you're building CSV data you might need to convert integer values to strings yourself, as parseCSV just casts all input values to strings without any special logic.

If it's when you're parsing CSV data, are you performing any type conversations on the output data from parseCSV? Cause parseCSV itself doesn't perform any kind of type casting/conversion and should just return strings as they appear in the CSV input.

**Comment by tahseen2k8** [comment]
Got it thanks for reply @jimeh
