### ISSUE TITLE
Standards compliant vs wikipedia compliant

### ISSUE THREAD

**Issue by ftrotter** [parsecsv/parsecsv-for-php#64]
The relevant standard here is RFC 4180 https://www.ietf.org/rfc/rfc4180.txt

The wikipedia article talks about what the RFC says but it also discusses lots of ways to handle CSV files that have little to do with the specific CSV standard.

Is the goal of this project to be compliant with the wikipedia article (which is what the readme currently says) or the RFC?

Either way.. thanks for the great code!

-FT

**Comment by jimeh** [comment]
The idea is kind of to be compliant with both. The RFC is pretty straight forward and strict, but most real world CSV files don't exactly follow the RFC. The idea was always to try to be able to parse as wide range of real world CSV files (and their quirks) as possible.

Admittedly there hasn't been much in terms of large changes to the project for years, and that includes the readme too. But last I checked it did adhere to the RFC, while also being able to deal with a few other weird quirks you might come across.
