### ISSUE TITLE
Timezone Error

### ISSUE THREAD

**Issue by ChristianGrech** [parsecsv/parsecsv-for-php#65]
Getting a timezone error instead of data in excel. `Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods an`.

Fixed by adding `date_default_timezone_set("Europe/London")`  in the output method.

**Comment by Fonata** [comment]
Thanks for sharing your solution! 😊 

In my view, nothing needs to be changed with parseCSV.
