### ISSUE TITLE
[enhancement] Line-Based API?

### ISSUE THREAD

**Issue by ccoenen** [parsecsv/parsecsv-for-php#66]
I am parsing a 150MB CSV, and i (quickly) ran into `fgetcsv`'s shortcomings. One advantage it has, though, is that the number of lines was pretty much irrelevant.

In the examples and in the code, I can't really find an equivalent, though. It seems that the line by line stuff is bundled up in [parse_string](https://github.com/parsecsv/parsecsv-for-php/blob/master/parsecsv.lib.php#L639) and the file is always read "as a whole" in [_rfile](https://github.com/parsecsv/parsecsv-for-php/blob/master/parsecsv.lib.php#L1131).

Is there a way to just pass line data to parse_string as a workaround?

**Comment by ccoenen** [comment]
I need my memory_limit of 2048M, to parse a 150MB csv :-(

**Comment by ccoenen** [comment]
I have a workaround for anyone else with the same problem. But I really think there whould be some way to _not_ use this approach.


```php
$csv = new parseCSV();
$csv->delimiter = ',';
$csv->enclosure = '"';
$row = 0;
$header = "";

if (($handle = fopen($filename, "r")) !== false) {
	fseek($handle, 3); // skip BOM, this may not be neccessary for your case!
	while (($line = fgets($handle)) !== false) {
		$row++;
		if ($row < 2) {
			// skip and store header line for later use
			$header = $line;
			continue;
		}

		$csv->parse($header.$line); // prepending $header for every line.
		var_dump($csv->data);
	}
	fclose($handle);
}
```

**Comment by slavafomin** [comment]
Yeah, I think such files should be read line-by-line, +1 for this.

**Comment by susgo** [comment]
I think, I miss something because I'm new to the project, but why does `limit` and `offset` do not work in this situation? Sorry, if this is trivial. I don't see it in the moment

**Comment by ccoenen** [comment]
I don't want to limit anything, I want the whole file. But in my case, it's not neccessary to have it in memory all at once. I'm processing each line and then move on to the next.

**Comment by Fonata** [comment]
Your workaround above only works if your cells never have embedded line breaks. You can still use  `limit` and `offset`  to get the whole file: by processing it in chunks: keeping  `limit` constant (e.g. 100) and increasing `offset`. You can use @susgo's `getTotalDataRowCount()` function to calculate how many chunks you have.

Alternatively can also try the following repositories for parsing big files. For each repository below, I list the month of the first commit (for ParseCsv `git log --reverse` prints Aug 2007):
- Jan 2012: https://github.com/nuovo/spreadsheet-reader
- Dec 2012: https://github.com/goodby/csv
- Dec 2013: https://github.com/thephpleague/csv
- Jan 2015: https://github.com/box/spout

Pull requests are welcome if there is a feature that 
- you need and
- these four repos lack.

**Comment by ccoenen** [comment]
In my case, the csv can't have multiline data (yes, sounds like one of the assumptions that is about to be broken, but I also generate the CSV, so I'm quite certain). My workaround "works for me" for the moment.

I just thought, a streaming interface would be nice. I didn't know the limit/offset thing before today, probably I didn't find it because it's not very prominent in the README (and I didn't go through all the examples back when I found this library).

**Comment by susgo** [comment]
I have updated the readme here #129

**Comment by susgo** [comment]
Now I see, our solutions will not help you as the file is already read (in all cases). Sorry for not checking it before answering. I agree that this feature would be useful.

**Comment by ccoenen** [comment]
Good addition to the readme! I guess this will be good enough for most use cases. I have a workaround in place (which I'll continue using for the time being), and nobody else reported that problem. I'll close this ticket?
