### ISSUE TITLE
Creation of new columns works but headers not appended.

### ISSUE THREAD

**Issue by MattAds** [parsecsv/parsecsv-for-php#68]
You can add new columns to the data and persist them with $csv->save().
However when this is done the keys added to the data set are not added to the headers.
I suppose it might be hard to ensure that added rows are done uniformly accross the data so maybe this is not desired functionality however it suited my purposes.
Is there a mechanism to at least manually edit the header line in this library? Would be useful.

**Comment by jimeh** [comment]
I have to admit the use case of adding columns is not something that's really been thought about. As such it's up to you to ensure all your data rows have the same number of values, and also that the internal list of columns for a parseCSV instance is updated.

The data side is pretty simple, but as for the internal list of columns kept by parseCSV, you can update that by simply adding additional values to the `$csv->titles` array. For details on how the array is used, you can check the [relevant code](https://github.com/parsecsv/parsecsv-for-php/blob/4f144f2662af4f630a7bdc76970e987a178ba597/parsecsv.lib.php#L831-L839) in in the `unparse()` method.

Additionally you can also pass in a complete list of fields/columns to the [`save()`](https://github.com/parsecsv/parsecsv-for-php/blob/4f144f2662af4f630a7bdc76970e987a178ba597/parsecsv.lib.php#L435) method itself. However this would simply ensure the file written to disk has the correct headers, it wouldn't update the parseCSV instance's internal list, which might or might not be a problem depending on what you're doing with the instance after you call save.

**Comment by MattAds** [comment]
@jimeh Thanks very much for the quick response.You've allowed me to tie up this project before lunch.
$csv->titles is exactly what I need. Nice library, pleasure to use. :+1:

**Comment by jimeh** [comment]
Glad to help :)
