### ISSUE TITLE
Is it possible to use another less memory intensive structure?

### ISSUE THREAD

**Issue by kervinhexasoft** [parsecsv/parsecsv-for-php#69]
When I try to load large number of rows, the RAM usage goes above the 512MB I allocated for my PHP. Would be great if it is possible to store the data in a less memory intensive structure as opposed to the standard PHP array which is a memory hog.

**Comment by Fonata** [comment]
Probably not. However, you can always read or write line by line. That will be slower but require much less RAM. 

To write line by line, supply `true` as the 3<sup>rd</sup> parameter of ``save()``. 

Reading line by line is easy if no cell contains a newline. You can use `ftell` and `fgets` to iterate. If you expect newlines within cells, use the `limit` field to parse logical line for logical line along with some clever logic. Here is an example for the easy case, taken from a Drupal 8 module. Drupal's Batch API gives the user a nice progress bar and calls the function until `$context['finished']` is no longer set (or equals 1). This way, parsing many gigabytes of CSV data can be done with 512 MB RAM:

````php
function _import_batch($file_to_import, &$context) {
  $f = fopen($file_to_import, 'rb');
  if (empty($context['results']['header'])) {
    $context['results']['header'] = fgets($f);
    $context['sandbox']['progress'] = ftell($f);
    $context['sandbox']['max'] = filesize($file_to_import);
  }
  else {
    $oCsv = new parseCSV();
    fseek($f, $context['sandbox']['progress']);
    $sLine = $context['results']['header'] . fgets($f);
    $context['sandbox']['progress'] = ftell($f);
    $oCsv->auto($sLine);

    $sStatus = process_single_row($oCsv->data[0]);
  }
  fclose($f);

  $context['message'] = $sStatus;

  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
  else {
    drupal_set_message($sStatus);
  }
}
````

Has anyone example code for reading huge CSV files with multiline cells? Please paste it here.
