### ISSUE TITLE
Not splitting Excel CSV files with quotes around lines

### ISSUE THREAD

**Issue by audas** [parsecsv/parsecsv-for-php#70]
The CSV exported from EXCEL returns it with quotes. However these are not being detected so headers are treated as a single array node for example (as are all other lines).

Example of Google Contact Fields Headers -

From Excel

"Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory....etc"

Returned from parsecsv-for-php

[titles] => Array
        (
            [0] => Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory..... etc
        ) 

Any ideas on why this is happening ?

**Comment by jimeh** [comment]
It sounds like the Excel document is badly formatted. Something like this with all values in the A column:

![screenshot_26_10_2015_13_49](https://cloud.githubusercontent.com/assets/39563/10730525/6dd9937a-7be8-11e5-8df9-204a62f65b9c.png)

Would yield a CSV file like what you're seeing:

```csv
"Name,Family Name,Age"
"John,Smith,34"
```

While the following Excel document:

![screenshot_26_10_2015_13_51](https://cloud.githubusercontent.com/assets/39563/10730572/bcd8734c-7be8-11e5-8352-e6cdb2b4c80f.png)

Would produce:

```csv
"Name","Family Name","Age"
"John","Doe","34"
```

If that's not the case though, please provide some additional information.

**Comment by audas** [comment]
Thanks for your reply, which has solved the problem.


However if I open the two CSV files in notepad++ they both appear exactly the same - except one has lines terminating wrapped in quotation marks, the other does not - that is the only difference.

If one exports contacts from GMAIL then there are two options - one for GMAIL or OUTLOOK - the only difference between these being the quotation marks.

When wrapped in quotation marks this code fails directly from GMAIL export.

Opening the two in EXCEL reveals your response.

I would have thought that this code could handle the variations in line terminations - which is essentially all this is ?

Sam

**Comment by jimeh** [comment]
Strange. I just tried exporting my contacts from Gmail and regardless of which CSV option I picked it exported fine.

As for parseCSV handling the variation you've come across, I'm afraid it's not a CSV variation, but more of a broken file. Double quotes are used to for fields which contain commas inside of them. So in effect, wrapping a whole line in double quotes, is valid CSV containing a single column.

Here's an example that uses `,` as part of the `Author` value:

```csv
Name,Author,Price
The Da Vinci Code,"Brown, Dan",10.00
```

And if we stripped that CSV down to just the Author column:

```csv
Author
"Brown, Dan"
```

As you can see, there's sadly no way to distinguish between a single-column CSV dataset and the oddly formatted one you've come across.

**Comment by Fonata** [comment]
I don't think there is anything we can do within the code of this project to prevent the experience described above. 

Thus, I'll go ahead and close this issue. If more information comes along, feel free to re-open it.
