### ISSUE TITLE
double line endings

### ISSUE THREAD

**Issue by dampfklon** [parsecsv/parsecsv-for-php#75]
### Steps to reproduce

$csv = new parseCSV();
$csv->parse('someFile.csv');
$csv->linefeed = "\r\n";
$csv->save('otherFile.csv');
### Expected behaviour

otherFile.csv has \r\n Line Endings
### Actual behaviour

otherFile.csv has \r\r\n Line Endings
### Server configuration

**Operating system**: Win10

**PHP version:** 7.0.1

I could fix the problem by changing the write mode in the save function from

``` php
       $mode = ($append) ? 'at' : 'wt';
```

to

``` php
        $mode = ($append) ? 'ab' : 'wb';
```

**Comment by Fonata** [comment]
I could confirm this bug and am currently writing a PHPUnit test to catch it. I expect a fix in the master branch by February.
