### ISSUE TITLE
Encoding changed only when parsing files

### ISSUE THREAD

**Issue by borys-p** [parsecsv/parsecsv-for-php#76]
Hi,

It seems that the iconv() conversion takes place only when parsing files, not when parsing data from string. It's a little inconsistent and I have to add my own conversion, although there's one in the parsecsv library.

**Comment by Fonata** [comment]
Indeed, thanks for letting us know. You could call `load_data` with your string before calling `parse_string` without any parameters.

**Comment by borys-p** [comment]
Still, it should be documented

**Comment by Fonata** [comment]
Will do.

**Comment by borys-p** [comment]
Thanks!
