### ISSUE TITLE
modify csv titles

### ISSUE THREAD

**Issue by arafay696** [parsecsv/parsecsv-for-php#82]
*_How to modify csv titles: *_
i try: 
$csv->titles = array('fname','LastName','EmailAddress','paxContactNo','paxGenderID','paxAgeGroupID','BookingCode');

$csv->save();

**before:**
FirstName,LastName,EmailAddress,paxContactNo,paxGenderID,paxAgeGroupID,BookingCode

**After: it changes the syntax of file like this:**
"fname""LastName""EmailAddress""paxContactNo""paxGenderID""paxAgeGroupID""BookingCode"

is it okay or i have to change?

**Comment by Fonata** [comment]
For now, there is not enough information here to solve this old issue.

**Comment by susgo** [comment]
I think we have working tests for this situation now. Could you please check again if this works for you now?

**Comment by susgo** [comment]
I think this issue can be closed?

**Comment by williamknauss** [comment]
@susgo - Just for clarification - are you ready for this ticket to be closed?

**Comment by susgo** [comment]
I think so. We can reopen it when it does not work for @arafay696 but then we need more information. Alternatively, we could use a label that we are waiting for feedback. What do you think?

**Comment by williamknauss** [comment]
My preference is to close tickets even if we are waiting on feedback from a user. It makes the repository seem less cluttered and doesn't give any negative viewpoints at "first glance" when someone new is visiting the repository. However I  believe in democracy so I take take it to a vote! :)

**Comment by mojadadi** [comment]
Great
