### ISSUE TITLE
Could I change the column's id when I parse the csv?

### ISSUE THREAD

**Issue by paoloromano** [parsecsv/parsecsv-for-php#84]
During the parse i would to change the id of column with id=4 for example. Is it possible?
Thanks.

**Comment by susgo** [comment]
Could you give us an example? I think that should be a post parse task and therefore it should be implemented as an extension. Also it makes the library more complex. But when you give us more information, I'm sure we can help you and may be extend the code here.

**Comment by susgo** [comment]
I close this issue for now. Please feel free to reopen it, if you need more information / help on solving it.
