### ISSUE TITLE
Output method always produces headers and outputs directly to browser

### ISSUE THREAD

**Issue by skunkbad** [parsecsv/parsecsv-for-php#87]
Sure, you can set $this->output_filename to NULL before calling the output method, but the doc block for the method should reflect that. As it is now, one would expect the method to return a string if the first parameter is set to NULL.

In my modified parseCSV.php file, I just commented out lines 459 through 461:

```
    /*if (empty($filename)) {
        $filename = $this->output_filename;
    }*/
```

**Comment by Fonata** [comment]
Good catch. Instead of fixing the code, I fixed the docs. 

Another solution: You can call the `unparse()` function to get the string.
