### ISSUE TITLE
Error with enclosures on last item of last row without an end of line character

### ISSUE THREAD

**Issue by adrianbj** [parsecsv/parsecsv-for-php#89]
My understanding is that the CSV spec doesn't requirement an EOL character on the last row, so I wonder if this parser should handle this better.
```
Item1, "Item 2"
```
will result in: `Item 2"` with the quote on the end.

So long as I ensure there is an EOL then there is no problem.

Without the EOL, you get a PHP Notice referencing this line: https://github.com/parsecsv/parsecsv-for-php/blob/4f144f2662af4f630a7bdc76970e987a178ba597/parsecsv.lib.php#L700

**Comment by Fonata** [comment]
Thanks for bringing this up. Indeed, this happens if you call `parse_string` directly. 

Please call `auto` or `parse` instead, which will internally add the EOL around [line 846](https://github.com/parsecsv/parsecsv-for-php/blob/master/parsecsv.lib.php#L846)

**Comment by adrianbj** [comment]
@Fonata - I am actually calling `parse` 

This is my code:
```
        // if there is no new line at the end, add one to fix issue if last item in CSV row has enclosures but others don't
        if(substr($csvData, -1) != "\r" && substr($csvData, -1) != "\n") $csvData .= PHP_EOL;

        require_once __DIR__ . '/parsecsv.lib.php';

        $rows = new parseCSV();
        $rows->encoding('UTF-16', 'UTF-8');
        $rows->heading = $namesFirstRow;
        $rows->delimiter = $delimiter == "tab" ? chr(9) : $delimiter;
        $rows->enclosure = $enclosure;
        $rows->parse($csvData);
```

I have problems without that first line. I think you could replace that block around 846 with my first line and things would be fine. It's probably a Mac vs PC thing. My version should fix it for both.

**Comment by Fonata** [comment]
Thanks! I’ll research this. At the very least, we’ll need test examples to document the desired behavior.

**Comment by Fonata** [comment]
@adrianbj it is potentially fixed by now. I'd like to add a PHPUnit test though. Is there any chance you could attach a CSV file here? 

You may remove parts that should remain private, but please leave field separators, line ends, enclosures and such as they are.

**Comment by adrianbj** [comment]
Thanks @Fonata - that seems to work fine. Here is the result with the new version. I can attach a csv file, but all you really need is a string with:

```
$csvData = 'Item1, "Item 2"';
```

On another note - I should probably raise a new issue, but notice the extra blank space before "Item 2" in titles[1] - same happens for all subsequent CSV "columns" when using enclosures. Also, doesn't matter if `$rows->heading = false;` so that line is returned as "data"

![image](https://user-images.githubusercontent.com/871211/35759186-de9c5dcc-082c-11e8-93ed-9d398d9c7261.png)

**Comment by Fonata** [comment]
My understanding of CSV is that the enclosing char `"` should touch the field delimiter. In your example, there is a space. 

I'm not sure how the majority of CSV implementations would see this, but there is certainly ambiguity. I guess, the present philosophy of this project is to never reject CSV files (exceptions and such).

**Comment by adrianbj** [comment]
> My understanding of CSV is that the enclosing char " should touch the field delimiter. In your example, there is a space.

Yes of course - sorry for the confusion on that - my fault.

Back to the actual issue - are you happy with this is a test case?

```
$csvData = 'Item1,"Item 2"';
```

**Comment by Fonata** [comment]
Indeed, we've added your test case to the PHPUnit tests:  `testMissingEndingLineBreak()`.
