### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by pws2016** [parsecsv/parsecsv-for-php#90]
How i can know my encoding file?
i have upload form to can user upload his csv but i have error of encoding so must know the original encoding file to can use the encoding function to UTF8!
thanks

**Comment by steffengrahl** [comment]
you can use mb_check_encoding on a given string. to use mb_check_encoding read the whole file with file_get_contents and you can check the encoding. 

documentation for mb_check_encoding http://php.net/manual/de/function.mb-check-encoding.php
documentation for file_get_contents http://php.net/manual/de/function.file-get-contents.php

**Comment by Fonata** [comment]
Potentially, also a BOM might be present and interfering. In 20 days at the latest, parseCSV will be a little smarter in reading CSV data with a BOM - see #106.
