### ISSUE TITLE
Text fields appear concatenated

### ISSUE THREAD

**Issue by gramagrass** [parsecsv/parsecsv-for-php#91]
In my .cvs a text field with several phrases (each in a line when I see the file in a text editor) appear like a solid chunk of text when running it through parsecvs. Is a problem with the encoding in the library?

**Comment by grundum** [comment]
nevermind, using nl2br();

**Comment by Fonata** [comment]
I'll go ahead and close this. Feel free to re-open if you have an example file parseCSV doesn't seem to handle well.
