### ISSUE TITLE
parseCSV not found?

### ISSUE THREAD

**Issue by websanova** [parsecsv/parsecsv-for-php#93]
So I'm doing a `require` and can `echo` but still gives not found?

~~~
require_once base_path() . '/vendor/parsecsv/php-parsecsv/parsecsv.lib.php';
echo base_path() . '/vendor/parsecsv/php-parsecsv/parsecsv.lib.php';
echo substr(file_get_contents(base_path() . '/vendor/parsecsv/php-parsecsv/parsecsv.lib.php'), 0, 100);
~~~

Still gives not found ?

~~~
new parseCSV($file);
~~~

No idea why it would be coming up not found.

**Comment by Fonata** [comment]
Sorry we weren't of help earlier. I'll close this issue now because so much time has passed. 

Feel free to open it again in case you can paste the exact error message.
