### ISSUE TITLE
How to get Total Rows in CSV file?

### ISSUE THREAD

**Issue by sajidshah** [parsecsv/parsecsv-for-php#95]
What is easy way to get total records in csv file. I have a file over 30k rows. Is there a simple way to get total count? There is html data in on of my column too, which includes multiple line breaks. So total line will not give exact number. Wondering if there is any quick way other than reading entire csv and checking array size?

**Comment by shazahm1** [comment]
I do it like this:

``` php
$csv = parseCSV();
$csv->auto( $file );
count( $csv->data );
```

**Comment by fiedsch** [comment]
Ok, but that is

>   reading entire csv and checking array size?

which @sajidshah wanted to avoid

**Comment by shazahm1** [comment]
@fiedsch , yeah, I read that now. Honestly, I didn't read the last sentence...

To get the number of rows, you have to parse the file... one way or another.

This would be a more performant method:

https://stackoverflow.com/a/43075929/5351316

Problem is @sajidshah said he has HTML with line breaks in the CSV file. I would assume that the only way to get reliable count is to actually parse the file which should not be an issue with a 30K line file.

**Comment by koiosoft** [comment]
My answer can be silly. But what about, copy the file and add at the end, a line that guarantees that it is the last (with some wildcard). Then you can read sequentially until you get the last line.

Understand the utility of knowing the total of Lines, if you want to have a kind of progress bar.

Now imagine, that you are reviewing line by line and rebuild the file as it is. Each time you add N number of lines, you can see the size of the file and buy it with the original file. With this you can handle the% for a progress bar.

A little imagination sometimes helps. :)

**Comment by sajidshah** [comment]
@shazahm1 @fiedsch @koiosoft 

Thank you for looking into this question. Really appreciate your help. 
SplFileObject can be a way of doing it BUT unfortunately it also returns the last line as total records which is not correct (because of multiple line breaks with in column data).

I tried some ssh commands too but they are also not very useful to get accurate total rows with these line breaks. 

The count( $csv->data ); is definitely right way of doing it BUT reading those 30k records reaches to timeout and if I increase the max time execution it then takes forever in just calculating the total rows. (the file is like approx 50mb). 

For now this is what I am doing, removed all line-breaks with in column making sure each line has only one row of data. Once the file is organized then i get the last line of the file which returns more accurate count.

Once again thank you for your help.
