### ISSUE TITLE
CSV with MAC

### ISSUE THREAD

**Issue by pws2016** [parsecsv/parsecsv-for-php#98]
Hello,
i build a CSV file with MAC and i have encoding error .. after upload the file i see empy page!
How i can fix this?

**Comment by Fonata** [comment]
Sorry we weren't of help earlier. I'll close this issue now because so much time has passed. 

Feel free to open it again if you still have issues. We'd need to know if your problem is
- related to parsing an existing CSV or 
- writing a CSV to disk or
- outputting a CSV to the browser?
